nome = input('Digite seu nome completo: ').strip()
print(f'Seu nome em letras maiúsculas é {nome.upper()}.')
print(f'Seu nome em letras minúsculas é {nome.lower()}.')
print(f'Seu nome tem {len(nome) - nome.count(' ')} letras.')
separa = nome.split()
print(f'Seu primeiro nome é {separa[0]} e tem {len(separa[0])} letras.')